import { PIPELINE_STATUS } from "kadesh/constants/constans";

export const PIPELINE_BAR_COLORS: Record<string, string> = {
  [PIPELINE_STATUS.DETECTADO]: "#64748b",
  [PIPELINE_STATUS.SELECCIONADO]: "#3b82f6",
  [PIPELINE_STATUS.CONTACTADO]: "#6366f1",
  [PIPELINE_STATUS.SIN_RESPUESTA]: "#d97706",
  [PIPELINE_STATUS.INTERESADO]: "#059669",
  [PIPELINE_STATUS.CREANDO_PROYECTO_PROPUESTA]: "#0284c7",
  [PIPELINE_STATUS.PROPUESTA_ENVIADA]: "#0891b2",
  [PIPELINE_STATUS.SEGUIMIENTO]: "#7c3aed",
  [PIPELINE_STATUS.EN_NEGOCIACION]: "#e07c3a",
  [PIPELINE_STATUS.PROPUESTA_ACEPTADA]: "#16a34a",
  [PIPELINE_STATUS.PROPUESTA_RECHAZADA]: "#dc2626",
  [PIPELINE_STATUS.CERRADO_GANADO]: "#15803d",
  [PIPELINE_STATUS.CERRADO_PERDIDO]: "#b91c1c",
  [PIPELINE_STATUS.DESCARTADO]: "#737373",
};

export const PIPELINE_ORDER = Object.values(PIPELINE_STATUS);

export const OPEN_PIPELINE_STATUSES = new Set<string>([
  PIPELINE_STATUS.DETECTADO,
  PIPELINE_STATUS.SELECCIONADO,
  PIPELINE_STATUS.CONTACTADO,
  PIPELINE_STATUS.SIN_RESPUESTA,
  PIPELINE_STATUS.INTERESADO,
  PIPELINE_STATUS.CREANDO_PROYECTO_PROPUESTA,
  PIPELINE_STATUS.PROPUESTA_ENVIADA,
  PIPELINE_STATUS.SEGUIMIENTO,
  PIPELINE_STATUS.EN_NEGOCIACION,
  PIPELINE_STATUS.PROPUESTA_ACEPTADA,
]);

export const WEEKLY_BAR_COUNT = 8;
export const TOP_BREAKDOWN_COUNT = 6;
